source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'DynamicAssociatedProperties_Tests', :exclusive => true do
  pod "DynamicAssociatedProperties", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
